apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-token
  namespace: services
spec:
  encryptedData:
    password: AgDTU4kaDBsCWA/5def5sHAprION+er5CE3kuU3XZ7jd3x3hzqM4G2lZx101OQ5YCMfCk4b3xJdJn7CgEVTFAUsixLENKaX5NQ0y7JyWYS4gYEcmKYWm5O/OE8Ddjw2LEohAnCxxqIyFDTpcHn6onTDGwJVyU0eLN05j5FIR9cua+W8ha3R3qKNN/P4whZHgtxaVvVfak9Z8FPx5mEfjRkQMcxP7K5ghKazeApT9f8atYkdB7Ap1OTVzBPmVGTQQMILJ/tJAULpODd9343gOH6wfnLh5Oxfa7VkKASycweBMopvjE951Ix2qTujrNwP4NjWqYs8+khS1hzaJXik25cQPj/Zk9SyhIqO/zSiLrt1vPeR7Q7U+WIO/bOpy+BnBi+DiXvJhs3q3B32X2jkUXATGWm7Xb5q4ifYA0YLKuCWEqJfKdWQvEBlup0BeDCcA4/q64gadaHo8yAlGEAQglA8h8iix0mlHu6X8aimHtlcE6uSl1w2IMroskkj27+jWomifAlLk44fn878jdUYcZBV7iRwoeH7tk7YdeRe44aFHSi+VoC8eOZKRy9feVBWHOh/2oGAcMloHmT5dO7xewwe+0DSvbWq2vUDKGhJKXBV4dPNe8JPXtayKwTsHl6EPUBoTqDYTV2gAXue2nPk8yUtnhRVrU93/SA6TTLFe3MojPAL8kUsEXP4XcdVm3Xt7C6Sg9KHFtxdPm8VORvOvOnQJlGd2Qhl+V02SEN3rP/2I25dHwM8=
    username: AgDdawXdQlGpQ/yaYFFORYwomlHqs4iYLRiGhgPgA+zIpccRB9IDY/zve7C4JDmbjHtkD1jARlHmkQiqi0/wuV7Z7iPM3a7b0tFAL4hatVT59IRwGvpquPzc4//Po8Tp0gF49zYa69i3OZVrN/Phd6dDERUZ57uhFqrUq13Wye4nJ+J1fvvcNWew/i7iOSxDVi1NW9tPEqobddhFJNuHDGHiyucDIFZF+GLbC7mevyfyIuXcso/sEouf7SxW3cJTtCDCGcKi5Veryma/3UVdNs5goYdLOheXyg/rfIqvl1Wxat8uD9vjZHlr2k5U511/FMnvTw8Ko7c8XxH/90rYCF42QapU7Vr6d/txUtagZONPP2mTgnNa0L4u7cBksSIgiqLOtMo/ZwSA/HSTKcq8BwDzZR7od82yFkTc6r9HXXyd2gB0HHnRZ0URLcBIqljoLXOB66j5qmlOO1PFT9A8W5TfNmGWEyHajqZYmunjB+q2USmzgMaCEUAS3e1pR+48osUBqAJ+7wVxqR22Q7gnQi/Wvzbk6wPr4QW/wLqS9rqiAPGMn2suqf2BckyCZDdQA85aKPx93U0/ZVplFGmz3cYTZodI+7m7HNAq44Kv5zrEmRocXafQnaHq0wjBE2u94lcZ9UypnUrFqgKcGc+ngb3C3qdiH0G/lVrTim2BuCzlnRZNMsWrDjrvUgEl29dzHFh+f3QVxiMoyQ==
  template:
    data: null
    metadata:
      annotations:
        jenkins.io/credentials-description: dockerhub-token
      creationTimestamp: null
      labels:
        jenkins.io/credentials-scope: global
        jenkins.io/credentials-type: usernamePassword
      name: dockerhub-token
      namespace: services

