apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-token
  namespace: services
spec:
  encryptedData:
    password: AgBtp/AoRM3ayDyO3JK4NShQkm2K/F2BUo/lnmLQN3tfwjPLtNocrY0atXoLB31IcwYONjm8Oc+QC+WAZm2LQux5Tgw46ELweuwTNofQ8HqkD+2NUhu8rRSwyfVR6Hvg7G8G60qDkD82KTZxRw+Q0yQwXfGQZDZiplLj+ZPJa7RdoOEMA1gzrwTzmU0mup3kN2O+r8MGD5eURSpZgDiCBBCHcbNRNlFq8V9bWfrGZ99sHB481L26FQRAo3sJqeZZujWROGTRYaxO7AoshyzyUjpS/hqoE9BwGQ3MOtMfrDFgZqYIdfgklZhfSefeYVAJVm/08uKxFCO//dcR9wHVdYor8yOWoMd+IG0ACSdxiTfVPxbKSO9UtnUG9kPEAoRQqkIemXjT5HSUI4jkRYhcll2P1WwxEwrgdj8OTW5s5JcClhIk9NZKsBO5fBsP8od0zA6cLtGTmsibc/iiHXD8jtvYV33TQvXeG0ZkseYZF/9b5ESDpUJbsDIwhFvcC+cZtWZEfERoqfjWq8z2/kZsM/Bcg+DiPtDVUN23JecFUBM9H34XxeL8JSfpNtEqZ2yzdyjCLAc6BjGzFq5NpxVqYiyvUn+rNeH24kArtqdwTzeaRbxBO6RBxkQfepIBnuka8xoyhSVTjJQ1oAWnUlJxqscujQ2SbOXzmt5XptnG5sGRF9Q2d3Aqzto6vkCyct6hCZxpgjwmdh2km8yIrWNpQvVC1Gv1dVNi6ZBjDhJGioN9+nQLn+s=
    username: AgA9sJC5Rt8fwYeEgX/EF+qoz3g1YH5TNeVwoYa2OItPR7n5grMccxABOJXeP/WttEbgvErBlJ161vxNmDUOFoN/CLq3kKK2SsY8OwRRAOeuIbh4YZKuC6Gn55lp52GKfpT7zUn0nzIiQ3/APQ8JzXRctkQtH225UWsqRhTAF+1DkAh1Rgs90Px27Hp6Y5wTIL/acG9u7oYHGcV1cOBfAVF0/DJb3TaVx6QLn9Q16Mi/P4QgRWbtz7saN85b1PDNbAxokoHXxFRzUfgyQl0U/y0ZSYLS/g2autnSXtBTEYRBXWTb9bGwWMhqujlxU9UsRRRfh8oXNGBMcBah2rFPw15osOByCW7e/dlOd+QGRG5BXCI7FHC7TXWCubE2HVX1TDezDlL10ALNmdtZ14lbydwFMSwmLL8/GQzg7+iAzsApxAoHC9f3ppOacJPj7px8xfJAvdbQ6vzmDf3Z5DFg0n0WAa0pNJeTYMT3/WNr5wODvTH3u+m0MsT0dCMS5YDVJALrucsl31mVVNeLqkzeijB+/QhLBAiwsXPrVa0tpVsVm/TuZdCPF2akWefTfzeyLF2t4eE5P4/DQ9q3X0IwHpwf4x1LZq3JFclQvFPMuXuKPn4jGdEQNMrNLGCmF8sMPPBZLXTu9uL8LhnFP2snTY2mCn2XPQFeYvZkCACx2QayEmgdfzJD4aTH7SWjPwMhsszMdrw2ihHtUw==
  template:
    data: null
    metadata:
      annotations:
        jenkins.io/credentials-description: dockerhub-token
      creationTimestamp: null
      labels:
        jenkins.io/credentials-scope: global
        jenkins.io/credentials-type: usernamePassword
      name: dockerhub-token
      namespace: services

