apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-token
  namespace: services
spec:
  encryptedData:
    password: AgA5rSMHQUcADADfXIIps0IvppVkIjv40KKk91owQatyFwyODIkhD9DnOU3Zv/2V9R+D3b9IO4l4S8XTDeVm5Mc4qCL/yAyvirmFlBIma9YoZRPZCR+gkUNVhJztYLguYPxeHSCPNibE4/HuVRKVicvhdZJ4iHAp4qT7yd2qeBw5nvEqpPX6EKpJnfpyifZV1179DX2BfufK+8PuXrrMfy1QkCAfYc2LS6+eV0EA9LW08NInthoU8Np1hB3f3MMHKKR//C+oIeQLOhs4iRg9hg/PiXqJfgx0RTcUr/du22XNlAbVYO6yDdr9nRq//PtM9IHMwb0u1VRVMqSQzyHH6pVG0sTxcZ68s+b19ACoByWKAHpg3cLtddbk55tjcRCGBcc0jUasjPHf2f7/guINkBCCueSbyclbOOdmV8VAX5t0gEAg+SAt53GnoVRLG8oKVqv4WBuF6uC2R1FgK5fPu1SQRRREgMm0X/mV2y4r0PHRs33JPQuxCaOf643ooK/g4Hngn6UgZgCF6FjGQH9zL3ygb+oEWel1alI4wgNRsRXfcRVZJQzyxGr+Gtb6uLovttekJuT9NTTrNIdkAAl5V55V7y47xaODiQY5kOfTO1sWNkf6bN9aeaEHQAzfF+gS1i+U0oa81CTE8Zs6GugksP3O0/8SODzKp3JYqqzDSsCffbsBvROlbKX0A12IStdx7wUJ3rnixdBuB2Ta9zcivpf9UHI26DuyGPljKLgplUX7QLUJlTM=
    username: AgA14YR4TLAdqnGJjoLm6Ol1RKzgZkZelvGZkqDd8YcvBcbrNzjo8wxyYwDMJ/2Jql1CFNn5umFhblZzfHg2KxxSy/gPfi4XOZUiuLH1q9wMJKEul2lUJS4OLem0kABpfwPEIgHtkB9ErWMM7lSnjPIJ9ujGNpkLA51baJjCaXBZe13LD+oIJ3rrsRcILCNyyKUk1CiySsqsuRAHeNisiyRmWybJWAj/N3rjL7vvJpS7Wi4u8gjXeNASFkPuL2Z1kmmiGVgSKRrTZCmpqxuFqjA0dEPe47+wclMPZmvmlfb+T60opqwCkrGlKfyNUAUVgNI5WJJrZmOQ9ZEeS+dkrhkNaeOnB6TCTki3BOw42jxULSRV+uIZU7RFFHuwKLzXuZT6VxWQ0H2vKch8ZBHSc4EktOTZKoM3lpSkZ3j84XBPocxahAVCNMG2WeCZ4HpbWl8Zay3aI8H1GPCtyJmpPFGDgflyH9HDkgqB08daBkVZaNl8m7g5Pt3tzJTUgQjur7wypmuKUQJaqk01WF6alnaF/bTtRinXqbB7jbq4a8D09DQfDSQoFr65DeuhSTBr78NNSqtcWwo55VCjuW2mj9S9PXqtjg+FTswXWtHdyyW/iw9lhQwcz9c/TIQ5P1NS+ZBI7TXSXKQFnLwI/g6LQxPrLNzEWHdC8ELhmGUNmLlSnF8XMPBvEJ7FnFEnu6icIkbHezNaL7/oQw==
  template:
    data: null
    metadata:
      annotations:
        jenkins.io/credentials-description: dockerhub-token
      creationTimestamp: null
      labels:
        jenkins.io/credentials-scope: global
        jenkins.io/credentials-type: usernamePassword
      name: dockerhub-token
      namespace: services

