apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: master
spec:
  configurationAsCode:
    configurations: []
#      - name: jenkins-operator-user-configuration
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    basePlugins:
    - name: kubernetes
      version: "1.31.3"
    - name: workflow-job
      version: "1145.v7f2433caa07f"
    - name: workflow-aggregator
      version: "2.7"
    - name: git
      version: "4.10.0"
    - name: job-dsl
      version: "1.78.3"
    - name: configuration-as-code
      version: "1414.v878271fc496f"
    - name: kubernetes-credentials-provider
      version: "0.20"
    - name: workflow-multibranch
      version: "711.vdfef37cda_816"
    - name: ansicolor
      version: "1.0.1"
    - name: timestamper
      version: "1.17"
    - name: credentials
      version: "1074.v60e6c29b_b_44b_"
    - name: pipeline-stage-view
      version: "2.22"
    - name: github
      version: "1.34.3"
    - name: github-branch-source
      version: "1583.v18d333ef7379"
    - name: docker-workflow
      version: "1.28"
    # - name: pipeline-model-extensions
    #   version: "1.9.3"
    # - name: pipeline-model-definition
    #   version: "1.9.3"
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.332.1-lts-alpine
        imagePullPolicy: IfNotPresent
        env:
          - name: JENKINS_OPTS
            value: --prefix=/jenkins
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 256Mi
  seedJobs:
    - id: jenkins-operator
      credentialType: basicSSHUserPrivateKey
      credentialID: git-gl-test-ssh
      targets: "cicd/jobs/*.jenkins"
      description: "Main Gorilla Logic Challenge repository"
      repositoryBranch: main
      repositoryUrl: git@github.com:snwbr/gl-test.git
