apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-user-configuration
data:
  1-credentials.yaml: |
    credentials:
      system:
        domainCredentials:
        - credentials:
          - file:
              scope: GLOBAL
              id: "gcp_sa_key"
              fileName: "gcp_sa_key.json"
              secretBytes: "${base64:${readFile:${gcp_sa_key.json}}}"
