resources:
- jenkins_crds.yaml
#- jenkins-operator-user-configuration.yaml
- gcp-sa.yaml
- git-gl-test-ssh.yaml
- ingressroute.yaml
- jenkins_operator.yaml
- jenkins_instance.yaml

namespace: services
