resources:
- jenkins_crds.yaml
- gcp-sa.yaml
- git-timeoff-ssh.yaml
- git-gl-test-ssh.yaml
- github-app.yaml
- dockerhub-token.yaml
- ingressroute.yaml
- jenkins_operator.yaml
- jenkins_instance.yaml

namespace: services
