apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: services
spec:
  encryptedData:
    users: AgBpK9BmRpU3sXUPtZQ5wtkJTWwA42du89k/0K3DCs7Mus2t07IcneOH58oDWoms/sQnseQBxJ6QkjKpr4DlPeSThASyEpNSe3je/J8USseYlm92vc27RYP36GXX0rChHWnRAI8dZxQImpWNyKSVYsHR/VaIYC+HDepxZMBCBe2Hdhv/hz9SiGFIk+W+CkbGwKcHl/p1UDhHc9Mfs4lccry2IPyVRJ2QeYaBoIDGit/h9fVLOA+75extBxYAmcZT4OgbPClXDo6QDdnS3V14BnIz6b6h2RYTt/ncBrHSTbVFO8fOyT+POyi6vwb5bRMxPhEAy9LvsHJltednepfEkJ/tFM8QTd2Nyc61RktNpyxzwPgemGc1PnsO8bBl0A7m4n68wbjvZxxo7w6LUNQ9wW/22ntbDbxKbsNWBF9sNMi4UJzK2R9pzcjDvcYjjtx1w87JzqPd/ZhyR/HCLw8LIIlnWnu1278OsZB429/cxkAZQcYakJUlQLGNSSz+PpnHeXyCi1NUzQsjWjsznK17MwCk/neX2YTgHto6EdfOJPqin7sml6EmOSYXFvJJepbPlwWHqF9W+WR4GBaB87Y7FzgDdAAPTpGhmXCxIRO0wTforjIH20SQIGX7Fv35vLv3vFiI4ke7FhGY7obmGTve71l6M/fDpv4UYp0JueT3N68BmVZgdOuZ8w2guZHCqEKfRDyu7WoLQvzBAxCLqAUyyIr7M01MRuKe3wW1WyafXU0q7A0PDIH1HZsDjkeWfZXawACYrj8waOKrslNwcyiXjYMC0HL2QQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: services
