apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: services
spec:
  encryptedData:
    users: AgBOXWGYTreTYvnP7Pa6zD7tesEpCF86rfEZCp3tWNEbSXgH/wLtIEZ7T7OK0QLR6IVpTGFwM8f0d5lE9bKvZoBP3Maz+C1fe6378J9EnykKy8DykSz6Z8aatJDy4f64JjGXPc80qXcuRNovE2VXRWK5EWyCgaleZwndnowEHxpnl//lW+YEyYAy0bwP345zyT9ZeFhlhOX0XOuSPEsS8VeMgLauCNwP9Iq03bYwpnlk++o5ECtR9hVS1sWYoQ2OYxT4ppAulJihYjSHFgQPJiSdnUbF7thsSNc4Xd0EPIpdpZ/1ynUXlfVkQhKY0WcHZ7hQ5tJWDce85vM4ngizIC6yjr0JxbJQ91NfPqnC53/Yg/tsmwknTfxam+N/mUufnb463Hesc6KoHCHrT4Z44m/Lq6HIBv67vJlP7uXBRGWIxJL8xvRF/QLDeliKnSrwbPB40k/g6bUCg6uhzgrcYbXg6CKtaPbixM6hRx/sIiW0OAZTY/btuLopF9nRp+ER26yrc3qw7nxHOJSggHaxPHj2S0BgZguTzEsI823TP0zpd+i7MS0OhLfOY+aHy7rD558Sczk8gXbSMqOrzIYRbJddv53zrVns6oJJigmruwOFusqQqQvBw3ZDrd/9FQEhcKNzyIMe5bFu6p7IzQnwfB2nuLpr9C0q47Ia56E9kfrfsDuBBoaQHLoortp/ZpS7FoXGVNfL4LPpFla+ZWLLZAjqM/MO5DXXNKDA/Csu7X2EriUbkuwfRwkCBwdcrMq78vyZ7eBWnlF7zZJvfoEH1MIlzBBiUw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: services

